### PR TITLE
Add further mocking to complete the range of things affected by the mock EnvironmentVariables

### PR DESCRIPTION
**Pull request by ashleyfrieze**

### CODE REVIEW

**Comment by ashleyfrieze** [comment]
To resolve #40

**Comment by OrangeDog** [comment]
That's not enough.

`ProcessBuilder` will call `ProcessEnvironment.environment()`, expose it for changes, and then pass it to `ProcessEnvironment.toEnvironmentBlock()`.

The return value needs to be a fully operational `ProcessEnvironment` that maintains its own independent state,

**Comment by ashleyfrieze** [comment]
@OrangeDog  I think the return value of `environment` is supposed to be a `StringValues` and the `toEnvironmentBlock` takes a `Map` but assumes it's a `StringValues` and then calls the function on `StringValues` to render it to bytes.

This can be worked around by mocking `toEnvironmentBlock` on `ProcessBuilder` to work with a `Map` and not assume that it's `StringValues`, copying the algorithm from `StringValues` to render it to `byte[]`.

However, do you know how I can observe the behaviour of this in practice? As all of these are internals, I can't hack into them to test them at a low level without further illegal reflective access.

Where would I see that the ProcessBuilder is using the correct output of the above? Any thoughts?

Do any of the other mocking/testing libraries cover this eventuality? I suppose if you genuinely mutate the underlying map, the it applies everywhere.

**Comment by OrangeDog** [comment]
This is the code for those methods in OpenJDK 17 for Windows:

```java
@SuppressWarnings("unchecked")
static Map<String,String> environment() {
    return (Map<String,String>) theEnvironment.clone();
}

static String toEnvironmentBlock(Map<String,String> map) {
    return map == null ? null :
        ((ProcessEnvironment)map).toEnvironmentBlock();
}
```

Note that many instance methods are also overridden and/or overloaded to add additional checks and wrappers.

A test case:

```java
ProcessBuilder builder = IS_WINDOWS ? new ProcessBuilder("cmd", "/C", "set") : new ProcessBuilder("env");
builder.environment().put("FOO", "bar");
Process process = builder.start();
String finalEnv = new String(process.getInputStream().readAllBytes());
```

I have been working on a solution. I've got this far but it's still not working:
```java
Mockito.mockStatic(clazz, call -> {
    if (call.getMethod().getName().equals("environment")) {
        Map<String, String> env = new HashMap<>(replacementEnv);
        return Mockito.mock(clazz, subCall -> {
            try {
                return HashMap.class
                        .getMethod(subCall.getMethod().getName(), subCall.getMethod().getParameterTypes())
                        .invoke(env, call.getArguments());
            } catch (NoSuchMethodException ex) {
                return call.callRealMethod();
            }
        });
    } else if (call.getMethod().getName().equals("getenv")) {
        if (call.getArguments().length == 0) {
            return Collections.unmodifiableMap(replacementEnv);
        } else {
            return replacementEnv.get(call.getArgument(0, String.class));
        }
    } else {
        return call.callRealMethod();
    }
});
```

**Comment by ashleyfrieze** [comment]
I think it would prove easier to rewrite the `toEnvironmentBlock` method on `ProcessBuilder`. We can definitely unit test this using your example.

**Comment by OrangeDog** [comment]
As you're already statically mocking `ProcessEnvironment`, you may as well rewrite `toEnvironmentBlock(Map)` there in case something else calls it. However, I think the implementation depends on the target platform.

Then you can just return `new HashMap(replacementEnv)` from `ProcessEnvironment.envrionment()`.

**Comment by ashleyfrieze** [comment]
Thanks for your input @OrangeDog 

Sadly `readAllBytes` isn't on `InputStream` in Java 8, so I've done something clunky. Please feel free to feed back on it. Do you depend on this for some tests of your own?

**Comment by OrangeDog** [comment]
You should add Windows tests. I edited the example above to account for it.
I assume these tests get run on multiple Java versions too?

**Comment by ashleyfrieze** [comment]
Hey @OrangeDog  - it's easy to switch different tests in for Windows using JUnit 5 - I'll use your example and see what it does. I'm more keen on seeing the final behaviour than I am seeing the implementation. My view is that if it works when you spawn a process, then i'm happy.

**Comment by ashleyfrieze** [comment]
@OrangeDog  

>```java
>static String toEnvironmentBlock(Map<String,String> map) {
>    return map == null ? null :
>        ((ProcessEnvironment)map).toEnvironmentBlock();
>}
>```

If that's the JDK 17 implementation, no wonder you were trying to work out how we could coerce the map back into the process env!!! They've changed the internals from Java 8.

I'm testing on Java 8, but my local environment is Java 17. Let's see how this latest increment passes through the tests on windows. If it passes, I may ask you to pull it, build it, and try it out.?

**Comment by ashleyfrieze** [comment]
@OrangeDog if you have a spare Windows machine, can you pull this branch and see if you find any good reason why the `ProcessBuilder.start` is failing. I tried it with `cmd`, `/c`, `/set` and it didn't work. I've tried a few variations, but nothing obvious is coming up. Array out bounds exception... but that suggests that the command line I'm feeding it is empty, which it isn't...!

**Comment by OrangeDog** [comment]
@ashleyfrieze you're using `Arrays.asList` for some reason. Also it's `"/C", "set"`, not `"/c", "/set"`

**Comment by ashleyfrieze** [comment]
@OrangeDog  hey James - please will you pull down this version of this branch and try it out at your side. If you think it works, then we can release it properly. We managed to deal with the Windows foibles.

**Comment by ashleyfrieze** [comment]
> @ashleyfrieze you're using `Arrays.asList` for some reason. Also it's `"/C", "set"`, not `"/c", "/set"`

You can feed the values in as either var args or list. I think `/c` is the "correct" parameter, though windows is not case sensitive in this regard. `/set` was incorrect, but wasn't the root cause. The root cause was a difference in `ProcessEnvironment` and `ProcessBuilder` on the Windows version of the  JDK.

**Comment by ashleyfrieze** [comment]
@OrangeDog  - I appreciate you're busy. I'm going to drop this as a release, though. I think it's a move up from where we're at. Please raise a new issue if it doesn't work for you.

**Pull request merged**
