### PR TITLE
Move byte buddy version to properties

### PR DESCRIPTION
**Pull request by ashleyfrieze**
Relates to #89  and #87

### CODE REVIEW

**Comment by jorsol** [comment]
Hi @ashleyfrieze , is there any ETA for a new release containing this version of bytebuddy?

**Comment by ashleyfrieze** [comment]
@jorsol - scheduled for release with maven - give it a couple of hours

**Comment by ashleyfrieze** [comment]
@jorsol https://repo1.maven.org/maven2/uk/org/webcompere/system-stubs-core/2.1.7/

**Comment by jorsol** [comment]
Thank you! 💯

**Pull request merged**
